CREATE DATABASE KAFKA;

CREATE TABLE KAFKA.SOURCE_MOVEMENTS_TABLE (
ID INT AUTO_INCREMENT PRIMARY KEY,
MOV_COD VARCHAR(50),
STORE_COD VARCHAR(50),
YEAR_COD VARCHAR(4),
PRODUCT_COD VARCHAR(50),
MOV_TIMESTAMP TIMESTAMP,
MOV_QTA INTEGER,
INSERT_UPDATE_TIMESTAMP TIMESTAMP NOT NULL);

INSERT INTO KAFKA.SOURCE_MOVEMENTS_TABLE (MOV_COD,STORE_COD,YEAR_COD,PRODUCT_COD,MOV_TIMESTAMP,MOV_QTA,INSERT_UPDATE_TIMESTAMP)
SELECT 'MOV60','STORE8','2015','PROD3',TIMESTAMP '2018-12-13 00:02:03.000','3',CURRENT_TIMESTAMP;