CREATE DATABASE KAFKA;

CREATE TABLE KAFKA.SOURCE_MOVEMENTS_TABLE (
ID INT AUTO_INCREMENT PRIMARY KEY,
STORE_COD VARCHAR(50),
PRODUCT_COD VARCHAR(50),
MOV_QTA INTEGER,
INSERT_UPDATE_TIMESTAMP TIMESTAMP NOT NULL);

